Repository jadu/pulsar, pull requests merged in 2018-10, with the labels that each got.

#891 Remove vagrant configs in favour of docker
  .gitattributes
  .gitignore
  Gruntfile.js
  Vagrantfile
  docs/Local_development.md
  makefile
  package.json
  provisioning/playbook.yml
  provisioning/templates/php.ini.j2
Labels: patch, tooling

#896 Make sure quaternary nav works with button links
  js/NavMainComponent.js
  stylesheets/_component.datatables.scss
  tests/js/web/NavMainComponentTest.js
Labels: bug

#890 Closing subnav now removes is-active class from nav-item
  js/NavMainComponent.js
  tests/js/web/NavMainComponentTest.js
Labels: bug

#900 Stop default link underline from leaking to naked button styling
  stylesheets/_component.buttons.scss
Labels: bug

#897 Improved focus styles
  stylesheets/_component.breadcrumb.scss
  stylesheets/_component.button-groups.scss
  stylesheets/_component.buttons.scss
  stylesheets/_component.close.scss
  stylesheets/_component.datatables.scss
  stylesheets/_component.flash.scss
  stylesheets/_component.forms.scss
  stylesheets/_component.navigation.scss
  stylesheets/_component.progress-lists.scss
  stylesheets/_component.range-slider.scss
  stylesheets/_component.search.scss
  stylesheets/_component.select2.scss
  stylesheets/_component.tab-help.scss
  stylesheets/_component.toggle-switch.scss
  stylesheets/_palette.base.scss
  stylesheets/_structure.scaffolding.scss
Labels: a11y
