Repository jadu/pulsar, pull requests merged in 2018-04, with the labels that each got.

#782 Added missing theme classes and removed unneeded comments
  stylesheets/_component.navigation.scss
  views/pulsar/v2/helpers/nav.html.twig
Labels: bug

#794 IE9 Quaternary nav width fix
  stylesheets/_component.navigation.scss
Labels: bug

#800 Fix form helpers/macros to use aria-describedby when help text is used
  Gruntfile.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/color-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/color-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/compound-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/compound-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/email-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/email-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/password-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/password-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/tel-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/tel-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/url-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/url-help.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/MacroTest.php
  views/lexicon/forms/choice.html.twig
  views/lexicon/forms/compound.html.twig
  views/pulsar/v2/helpers/elem.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: a11y, bug

#796 Disable pointer events on disabled elements within a tooltip container
  docs/_components/tooltip.md
  docs/_sass/_base.scss
  docs/assets/code_examples/html_helpers/html/tooltip
  docs/assets/code_examples/html_helpers/twig/tooltip
  stylesheets/_component.tooltips.scss
Labels: bug

#791 Focus first input field after opening a modal
  js/libs/modal.js
  tests/js/web/ModalTest.js
  views/lexicon/tabs/modals.html.twig
Labels: a11y, enhancement, minor

#807 Stop multiple appended buttons from overlapping
  stylesheets/_component.input-groups.scss
  views/lexicon/forms/text.html.twig
Labels: bug, patch

#805 Close popovers when opening the secondary navigation
  js/NavMainComponent.js
  tests/js/web/NavMainComponentTest.js
Labels: bug, minor

#802 Improve Modal Accessibility Structure
  docs/_components/modal.md
  docs/css/styles.scss
  stylesheets/_component.modals.scss
  views/lexicon/forms/select2.html.twig
  views/lexicon/patterns/reporting/report.html.twig
  views/lexicon/tabs/datagrid.html.twig
  views/lexicon/tabs/modals.html.twig
  views/playground/admin-mappings/index.html.twig
  views/playground/integrations/singlepoint_six.html.twig
  views/playground/xfp-rules/templates.html.twig
Labels: a11y, minor

#792 Addition of Stepped Progressbar
  docs/_components/progress-bar.md
  docs/css/styles.scss
  package-lock.json
  stylesheets/_component.progress-bars.scss
  views/lexicon/forms.html.twig
  views/lexicon/html.html.twig
  views/lexicon/index.html.twig
  views/lexicon/modules.html.twig
  views/lexicon/tabs/progress_bars.html.twig
Labels: feature, minor

#808 Stop select elements needing two clicks to open in Firefox
  stylesheets/_component.forms.scss
  stylesheets/_component.select2.scss
Labels: bug

#811 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, patch

#810 Restore has-error / has-danger state classes
  stylesheets/_utility.states.scss
Labels: bug

#799 Add ability to add styled screenreader samples to documentation
  docs/_form-helpers/text.md
  docs/_form-helpers/textarea.md
  docs/_sass/_screenreader.scss
  docs/assets/code_examples/form_helpers/html/text
  docs/assets/code_examples/form_helpers/html/text-col
  docs/assets/code_examples/form_helpers/html/text-disabled
  docs/assets/code_examples/form_helpers/html/text-error
  docs/assets/code_examples/form_helpers/html/text-success
  docs/assets/code_examples/form_helpers/html/textarea
  docs/assets/code_examples/form_helpers/html/textarea-changed
  docs/assets/code_examples/form_helpers/html/textarea-col
  docs/assets/code_examples/form_helpers/html/textarea-error
  docs/assets/code_examples/form_helpers/html/textarea-rows
  docs/assets/code_examples/form_helpers/html/textarea-success
  docs/assets/code_examples/form_helpers/twig/text
  docs/assets/code_examples/form_helpers/twig/text-col
  docs/assets/code_examples/form_helpers/twig/text-disabled
  docs/assets/code_examples/form_helpers/twig/text-error
  docs/assets/code_examples/form_helpers/twig/text-success
  docs/assets/code_examples/form_helpers/twig/textarea
  docs/assets/code_examples/form_helpers/twig/textarea-changed
  docs/assets/code_examples/form_helpers/twig/textarea-col
  docs/assets/code_examples/form_helpers/twig/textarea-error
  docs/assets/code_examples/form_helpers/twig/textarea-rows
  docs/assets/code_examples/form_helpers/twig/textarea-success
  docs/assets/image_examples/form-grid-4.png
  docs/assets/image_examples/form-grid-9.png
  docs/css/styles.scss
  views/pulsar/v2/helpers/form.html.twig
Labels: a11y, documentation
