Repository jadu/pulsar, pull requests merged in 2018-11, with the labels that each got.

#903 Allow datatables to accept a custom pageLength
  js/PulsarUIComponent.js
  tests/js/web/PulsarUIComponentTest.js
Labels: feature

#882 Fix invalid markup for required and guidance options in form helpers
  .gitattributes
  bower.json
  docs/_components/popover.md
  docs/_form-helpers/text.md
  docs/_form-helpers/textarea.md
  docs/assets/main.js
  js/index.js
  js/libs/popover.js
  js/main.js
  libs/bootstrapx-clickover/.bower.json
  libs/bootstrapx-clickover/README.md
  libs/bootstrapx-clickover/docs/assets/css/bootstrap-responsive.css
  libs/bootstrapx-clickover/docs/assets/css/bootstrap-responsive.min.css
  libs/bootstrapx-clickover/docs/assets/css/bootstrap.css
  libs/bootstrapx-clickover/docs/assets/css/bootstrap.min.css
  libs/bootstrapx-clickover/docs/assets/img/glyphicons-halflings-white.png
  libs/bootstrapx-clickover/docs/assets/img/glyphicons-halflings.png
  libs/bootstrapx-clickover/docs/assets/js/bootstrap.js
  libs/bootstrapx-clickover/docs/assets/js/bootstrap.min.js
  libs/bootstrapx-clickover/docs/examples.html
  libs/bootstrapx-clickover/docs/quickstart.html
  libs/bootstrapx-clickover/js/bootstrapx-clickover.js
  tests/js/web/PopoverTest.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-many-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-many-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance.html
  views/pulsar/v2/helpers/html.html.twig
  views/pulsar/v2/helpers/util.html.twig
Labels: bug, major

#906 [905] Add Multiple Selection for Select with Optgroup
  docs/_form-helpers/select.md
  docs/_form-helpers/select2.md
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-nested-selected-multiple-not-partial.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-nested-selected-multiple-not-partial.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-nested-selected-multiple.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-nested-selected-multiple.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-selected-not-partial.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-selected-not-partial.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-nested-selected-multiple.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-nested-selected-multiple.html.twig
  views/pulsar/v2/helpers/elem.html.twig
Labels: documentation, feature

#909 Add utility classes for clearing floats
  docs/utility-classes.md
  stylesheets/_utility.utilities.scss
Labels: documentation, feature

#911 Add sass/browserify compilation to Travis
  .travis.yml
  Gruntfile.js
  package-lock.json
  package.json
Labels: bug, tooling

#854 Changes for galaxies theme chooser UI
  js/PulsarUIComponent.js
  stylesheets/_component.cards.scss
  stylesheets/_component.forms.scss
  stylesheets/_component.lists.scss
  stylesheets/_component.modals.scss
  stylesheets/_component.status.scss
  stylesheets/_layout.settings.scss
  stylesheets/_structure.forms.scss
  stylesheets/_structure.grid.scss
  stylesheets/_utility.grid.scss
  stylesheets/_utility.utilities.scss
  stylesheets/pulsar.scss
  views/lexicon/index.html.twig
  views/playground/galaxies/admins.html.twig
  views/playground/galaxies/designer.html.twig
  views/playground/galaxies/index.html.twig
  views/playground/galaxies/security.html.twig
  views/playground/galaxies/settings.html.twig
  views/playground/galaxies/sites.html.twig
  views/playground/galaxies/theme.html.twig
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: enhancement, major

#914 Restore expected botton border to th cells in datatables
  stylesheets/_component.datatables.scss
Labels: bug

#916 fixed choice float issue
  stylesheets/_component.forms.scss
Labels: bug

#919 Stop popover trigger clicks preventing event bubbling
  js/libs/popover.js
  tests/js/web/PopoverTest.js
Labels: bug

#922 Fix issue where children of elements triggering popovers do not trigger popovers
  js/libs/popover.js
Labels: bug

#926 Update jstree dependency
  package-lock.json
  package.json
Labels: bug
