Repository jadu/pulsar, pull requests merged in 2018-09, with the labels that each got.

#881 Improved accessibility of toggle switches
  stylesheets/_component.toggle-switch.scss
  stylesheets/_structure.forms.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-class.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-label-hide.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch.html
  views/pulsar/v2/helpers/elem.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: a11y, enhancement, patch

#834 Fix a11y issues in navigation helper
  js/NavMainComponent.js
  stylesheets/_component.navigation.scss
  tests/js/web/NavMainComponentTest.js
  views/lexicon/base.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: a11y

#879 CMS Fixes for Pulsar 8.1.0
  src/Jadu/Pulsar/Twig/Extension/HelperOptionsModifierExtension.php
  stylesheets/_component.datatables.scss
  stylesheets/_component.tables.scss
Labels: bug, enhancement

#873 [801] Date helper does not support international date formats
  docs/_form-helpers/date.md
  docs/assets/code_examples/form_helpers/html/date-reverse
  docs/assets/code_examples/form_helpers/html/date-us
  docs/css/styles.scss
  js/PulsarFormComponent.js
  tests/js/web/PulsarFormComponentTest.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-append.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-bare.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-label-hide.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-label.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-prepend.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date.html
  views/lexicon/forms/date.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: feature

#887 [886] Add Placeholder Initialization Functionality for Date Helpers
  js/PulsarFormComponent.js
  tests/js/web/PulsarFormComponentTest.js
Labels: enhancement
