Repository jadu/pulsar, pull requests merged in 2018-03, with the labels that each got.

#774 Address 'more' navigation issues
  js/NavMainComponent.js
  stylesheets/_component.nav-list.scss
  stylesheets/_component.navigation.scss
Labels: bug

#764 Increased the width of the main nav to allow longer words in nav links
  stylesheets/_component.search.scss
  stylesheets/_config.variables.scss
Labels: enhancement

#776 Fix More Icon breaking on first time resize
  .gitignore
  js/NavMainComponent.js
  tests/js/web/NavMainComponentTest.js
Labels: bug

#788 Make greeter component more generic by changing brand images references
  stylesheets/_component.greeter.scss
  stylesheets/_config.branding.scss
Labels: enhancement

#784 Moved navigation color definitions in theme
  stylesheets/_component.navigation.scss
  stylesheets/_config.theme.scss
Labels: enhancement

#789 Navigation accessibility improvements
  js/NavMainComponent.js
  js/main.js
  stylesheets/_component.navigation.scss
  tests/js/web/NavMainComponentTest.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb-items.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-class.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-disabled.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-string-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-string.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-fragment-href-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-fragment-href.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-fragment-src-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-fragment-src.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href-with-src-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href-with-src.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-relative-href-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-relative-href.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-relative-src-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-relative-src.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-src-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-src.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_multiple.html
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/nav.html.twig
  views/pulsar/v2/helpers/tabs.html.twig
Labels: a11y, enhancement, patch

#779 Documentation restyle
  docs/.asset-cache/data7/0/1akx5u9p.d
  docs/.asset-cache/data7/2/32qbwlfr.d
  docs/.asset-cache/data7/4/7irwtpxd.d
  docs/.asset-cache/data7/5/1rgdkrce.d
  docs/.asset-cache/data7/6/2ykoy3lv.d
  docs/.asset-cache/data7/6/5qzmhcff.d
  docs/.asset-cache/data7/9/14zmalmy.d
  docs/Local_development.md
  docs/Rakefile
  docs/_config.yml
  docs/_includes/sidebar.html
  docs/_layouts/default.html
  docs/_layouts/page_pdf.html
  docs/_sass/_base.scss
  docs/_sass/_code.scss
  docs/_sass/_layout.scss
  docs/_sass/_posts.scss
  docs/_sass/_prettify.scss
  docs/_sass/_sidebar.scss
  docs/_sass/_syntax.scss
  docs/_sass/_type.scss
  docs/_sass/_variables.scss
  docs/assets/code_examples/layouts/html/head
  docs/assets/image_examples/Basic Layout with Sidebar Help/Box Model.png
  docs/assets/image_examples/Basic Layout with Sidebar Help/Example.png
  docs/assets/image_examples/Basic Layout.png
  docs/assets/image_examples/Basic Layout/Box Model.png
  docs/assets/image_examples/Masterswitch Layout with Sidebar Help/Box Model.png
  docs/assets/image_examples/Masterswitch Layout with Sidebar Help/Example.png
  docs/assets/image_examples/Piano Layout/Box Model.png
  docs/assets/image_examples/Piano Layout/Example.png
  docs/assets/image_examples/Reports Layout/Box Model.png
  docs/assets/image_examples/Reports Layout/Example.png
  docs/assets/image_examples/Settings Layout/Box Model.png
  docs/assets/image_examples/Settings Layout/Example.png
  docs/css/styles.scss
  docs/css/syntax.css
  docs/getting_started.md
  docs/pulsar.md
  images/grab-handle.svg
  package-lock.json
Labels: documentation

#777 Changed the way normalize.css is loaded into pulsar to make it more compatible with sass
  stylesheets/pulsar.scss
Labels: tooling

#785 Accessibility improvements
  docs/_styleguides/forms.md
  docs/assets/code_examples/styleguides/html/aria-label
  docs/assets/code_examples/styleguides/html/aria-labelledby
  docs/assets/code_examples/styleguides/html/hidden-label
  docs/assets/code_examples/styleguides/twig/aria-label
  docs/assets/code_examples/styleguides/twig/aria-labelledby
  docs/assets/code_examples/styleguides/twig/hidden-label
  docs/assets/image_examples/wave-tool.png
  js/FilterBarComponent.js
  stylesheets/_component.breadcrumb.scss
  stylesheets/_component.footer.scss
  stylesheets/_component.navigation.scss
  stylesheets/_config.variables.scss
  views/lexicon/tabs/cards.html.twig
Labels: a11y
