Repository jadu/pulsar, pull requests merged in 2018-02, with the labels that each got.

#761 Fix CMS integration issues with 7.0.0
  stylesheets/_deprecated.styles.scss
Labels: bug

#763 Fixed various radio/checkbox issues reported in 762
  stylesheets/_component.forms.scss
Labels: bug, patch

#766 Remove slider-container margin top on mobile
  stylesheets/_component.slider.scss
Labels: enhancement, patch

#767 Fix issue causing button groups to drop onto separate lines in settings sidebar
  VERSION
  bower.json
  composer.json
  package.json
  pulsar.json
  stylesheets/_component.forms.scss
Labels: bug

#770 Increased specificity of input group form controls
  stylesheets/_component.forms.scss
Labels: bug, patch

#772 Fix for radio inputs showing ticks when selected
  stylesheets/_component.forms.scss
Labels: bug, patch

#773 Fix issue causing secondary navigation to close when switching
  js/NavMainComponent.js
Labels: bug
