Repository jadu/pulsar, pull requests merged in 2018-08, with the labels that each got.

#853 [809] Close the table details panel when clicking outside of the details container
  js/TableDetailComponent.js
  tests/js/web/TableDetailComponentTest.js
Labels: enhancement

#860 Increase contrast ratio of text in footer
  stylesheets/_component.footer.scss
Labels: a11y

#863 Add bypass block example
  stylesheets/_structure.scaffolding.scss
  views/pulsar/layouts/base.html.twig
Labels: a11y

#862 Stop using empty alt attributes on user guide and notifications menus
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html.twig
  views/lexicon/includes/notifications.html.twig
  views/pulsar/v2/helpers/html.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: a11y

#864 Fix various issues with input groups and select2s
  stylesheets/_component.forms.scss
  stylesheets/_component.input-groups.scss
  stylesheets/_component.select2.scss
  stylesheets/_component.tables.scss
Labels: bug

#857 [855] Addition of Timeline styles from to Pulsar
  stylesheets/_component.panels.scss
  stylesheets/_component.timeline.scss
  stylesheets/_mixin.word-wrap.scss
  stylesheets/_override.shame.scss
  stylesheets/pulsar.scss
Labels: minor

#868 Improve labelling of main navigation links
  views/pulsar/v2/helpers/nav.html.twig
Labels: a11y, patch

#871 Fix no-wrap issues on collapsing datatables
  stylesheets/_component.datatables.scss
Labels: bug, patch

#867 Make sure nav helper correctly parses CMS heading IDs
  views/pulsar/v2/helpers/nav.html.twig
Labels: bug, patch

#866 Restore tab functionality with the presence of the new bypass block markup
  stylesheets/_layout.tabs.scss
Labels: bug, patch

#865 Add tabindexes to toolbar elements and make sure a logical tab order is maintained
  js/NavMainComponent.js
  stylesheets/_component.navigation.scss
  tests/js/web/NavMainComponentTest.js
  views/lexicon/includes/notifications.html.twig
  views/pulsar/components/nav_help.html.twig
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: a11y, minor
