Repository jadu/pulsar, pull requests merged in 2019-09, with the labels that each got.

#1016 1012_add-reduced-motion-support
  js/area/signin/signin.js
  stylesheets/_component.dropzone.scss
  stylesheets/_component.loading.scss
  stylesheets/_component.navigation.scss
  stylesheets/_component.tab-help.scss
  stylesheets/_component.table-detail.scss
  stylesheets/_layout.tabs.scss
  stylesheets/_mixin.media-queries.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/loading-label.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/loading-label.html.twig
  views/lexicon/tabs/loading.html.twig
  views/playground/login/index.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: a11y, enhancement, 🔥 breaking change

#1026 Add branding assets for Jadu Deployer, and new jadu purple colour palette
  Gruntfile.js
  images/branding/logo-deployer-black.svg
  images/branding/logo-deployer-white.svg
  images/branding/uol.svg
  images/favicons/deployer/android-chrome-144x144.png
  images/favicons/deployer/android-chrome-192x192.png
  images/favicons/deployer/android-chrome-256x256.png
  images/favicons/deployer/android-chrome-36x36.png
  images/favicons/deployer/android-chrome-384x384.png
  images/favicons/deployer/android-chrome-48x48.png
  images/favicons/deployer/android-chrome-512x512.png
  images/favicons/deployer/android-chrome-72x72.png
  images/favicons/deployer/android-chrome-96x96.png
  images/favicons/deployer/apple-touch-icon-114x114.png
  images/favicons/deployer/apple-touch-icon-120x120.png
  images/favicons/deployer/apple-touch-icon-144x144.png
  images/favicons/deployer/apple-touch-icon-152x152.png
  images/favicons/deployer/apple-touch-icon-180x180.png
  images/favicons/deployer/apple-touch-icon-57x57.png
  images/favicons/deployer/apple-touch-icon-60x60.png
  images/favicons/deployer/apple-touch-icon-72x72.png
  images/favicons/deployer/apple-touch-icon-76x76.png
  images/favicons/deployer/apple-touch-icon.png
  images/favicons/deployer/browserconfig.xml
  images/favicons/deployer/favicon-16x16.png
  images/favicons/deployer/favicon-194x194.png
  images/favicons/deployer/favicon-32x32.png
  images/favicons/deployer/favicon.ico
  images/favicons/deployer/mstile-144x144.png
  images/favicons/deployer/mstile-150x150.png
  images/favicons/deployer/mstile-310x150.png
  images/favicons/deployer/mstile-310x310.png
  images/favicons/deployer/mstile-70x70.png
  images/favicons/deployer/site.webmanifest
  images/favicons/src/favicon-deployer.svg
  stylesheets/_palette.base.scss
  views/lexicon/tabs/colours.html.twig
  views/pulsar/components/favicons-deployer.html
Labels: feature

#1028 Fix MS Tile deployer favicons
  Gruntfile.js
  images/favicons/deployer/android-chrome-144x144.png
  images/favicons/deployer/android-chrome-192x192.png
  images/favicons/deployer/android-chrome-256x256.png
  images/favicons/deployer/android-chrome-36x36.png
  images/favicons/deployer/android-chrome-384x384.png
  images/favicons/deployer/android-chrome-48x48.png
  images/favicons/deployer/android-chrome-512x512.png
  images/favicons/deployer/android-chrome-72x72.png
  images/favicons/deployer/android-chrome-96x96.png
  images/favicons/deployer/apple-touch-icon-114x114.png
  images/favicons/deployer/apple-touch-icon-120x120.png
  images/favicons/deployer/apple-touch-icon-144x144.png
  images/favicons/deployer/apple-touch-icon-152x152.png
  images/favicons/deployer/apple-touch-icon-180x180.png
  images/favicons/deployer/apple-touch-icon-57x57.png
  images/favicons/deployer/apple-touch-icon-60x60.png
  images/favicons/deployer/apple-touch-icon-72x72.png
  images/favicons/deployer/apple-touch-icon-76x76.png
  images/favicons/deployer/apple-touch-icon.png
  images/favicons/deployer/favicon-16x16.png
  images/favicons/deployer/favicon-194x194.png
  images/favicons/deployer/favicon-32x32.png
  images/favicons/deployer/mstile-144x144.png
  images/favicons/deployer/mstile-150x150.png
  images/favicons/deployer/mstile-310x150.png
  images/favicons/deployer/mstile-310x310.png
  images/favicons/deployer/mstile-70x70.png
Labels: bug
