Repository jadu/pulsar, pull requests merged in 2019-05, with the labels that each got.

#945 Initial attempt to standardise datatable options into an extendable method
  docs/_components/datatable.md
  js/PulsarUIComponent.js
Labels: feature

#966 Make pre/appended content be constrained by grid modifiers
  stylesheets/_component.forms.scss
  stylesheets/_component.input-groups.scss
  views/lexicon/forms.html.twig
  views/lexicon/forms/date.html.twig
  views/lexicon/forms/password.html.twig
  views/lexicon/forms/range.html.twig
  views/lexicon/forms/select.html.twig
  views/lexicon/forms/select2.html.twig
  views/lexicon/forms/text.html.twig
  views/lexicon/forms/time.html.twig
Labels: enhancement

#968 Color contrast of dropzone helptext now meet AA contrast
  stylesheets/_component.dropzone.scss
Labels: a11y

#973 Fixed issue where esc listener would fire when table detail not present
  js/TableDetailComponent.js
  tests/js/web/TableDetailComponentTest.js
Labels: bug

#981 Remove moment locale from .gitattributes
  .gitattributes
Labels: bug

#984 Spotted some log()s left in tableDetailComponent.js
  js/TableDetailComponent.js
Labels: chore
