Repository jadu/pulsar, pull requests merged in 2019-06, with the labels that each got.

#987 Datatables pagination a11y
  js/DataTables/dataTablesDrawCallback.js
  js/DataTables/dataTablesInitComplete.js
  js/PulsarUIComponent.js
  stylesheets/_component.datatables.scss
  stylesheets/_component.pagination.scss
  tests/js/web/DataTables/dataTableDrawCallbackTest.js
  tests/js/web/DataTables/dataTablesInitCompleteTest.js
  tests/js/web/PulsarUIComponentTest.js
  views/lexicon/tabs/pagination.html.twig
Labels: a11y

#990 Remove code related to twig.js
  package.json
  src/Jadu/Pulsar/Twig.js/Extension/ArrayExtension.js
  src/Jadu/Pulsar/Twig.js/Extension/AttributeParserExtension.js
  src/Jadu/Pulsar/Twig.js/Extension/RelativeTimeExtension.js
  src/Jadu/Pulsar/Twig.js/Extension/TabsExtension.js
  src/Jadu/Pulsar/Twig.js/Extension/UrlParamsExtension.js
  src/Jadu/Pulsar/Twig.js/Pulsar.js
Labels: chore

#989 Improvements to rules-v2 UI
  stylesheets/_component.rules.scss
  views/playground/xfp-rules/rules.html.twig
Labels: bug

#982 Stop focus outline appearing underneath adjacent elements
  stylesheets/_component.forms.scss
Labels: bug

#975 Improve how required choice helpers are marked up
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html.twig
  views/lexicon/forms/choice.html.twig
  views/pulsar/v2/helpers/elem.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: bug

#996 Fix safari table-detail content shift issue
  stylesheets/_component.table-detail.scss
  stylesheets/_component.tables.scss
  views/lexicon/patterns/table-detail/table-detail.html.twig
Labels: bug, patch

#993 Restore missing caret handle on select elements in Windows high contrast mode
  stylesheets/_component.forms.scss
  stylesheets/_component.select2.scss
  stylesheets/_mixin.mixins-to-organise.scss
Labels: a11y
