Repository jadu/pulsar, pull requests merged in 2019-12, with the labels that each got.

#1092 Add small image variation of media object
  stylesheets/objects/_object.media.scss
  views/lexicon/tabs/media.html.twig
Labels: feature

#1081 Make panel body overflow when contents exceed max-height
  stylesheets/_component.panels.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions-center.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions-inline.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions-invalid.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions-left.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions-right.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-actions.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-scroll.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-scroll.html.twig
  views/lexicon/tabs/panels.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: bug

#1082 Correctly position loading spinner when used next to main search elements
  stylesheets/_component.search.scss
Labels: bug

#1102 Repeater a11y fixes
  js/FocusManagementService.js
  js/Repeater/RepeaterComponent.js
  js/Repeater/RepeaterPreviewService.js
  js/Repeater/repeaterComponentFactory.js
  js/utilities/UniqueIdService.js
  tests/js/web/FocusManagementServiceTest.js
  tests/js/web/Repeater/RepeaterComponentTest.js
  tests/js/web/Repeater/RepeaterPreviewServiceTest.js
  tests/js/web/utilities/UniqueIdServiceTest.js
  views/lexicon/forms/repeater.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1093 form.choice improvements
  stylesheets/_component.choice.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-class.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-disabled.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-label-hide.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-label.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-multiple.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-few.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice.html
  views/pulsar/v2/helpers/elem.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1096 Bump rule heading and link styles to meet AA contrast
  stylesheets/_component.rules.scss
  stylesheets/_utility.states.scss
Labels: accessibility, bug
