Repository jadu/pulsar, pull requests merged in 2019-01, with the labels that each got.

#918 Make sure content within settings sidebar fits 100% width in responsive mode
  stylesheets/_layout.settings.scss
Labels: bug

#895 Adds twig file for symfony forms generation
  views/pulsar/v2/forms.html.twig
Labels: feature

#935 Various mobile improvements
  js/libs/tooltip.js
  stylesheets/_component.datatables.scss
  stylesheets/_component.filterbar.scss
  stylesheets/_component.forms.scss
  stylesheets/_component.modals.scss
  stylesheets/_component.navigation.scss
  stylesheets/_component.pagination.scss
  stylesheets/_component.piano.scss
  stylesheets/_component.search.scss
  stylesheets/_component.slider.scss
  stylesheets/_component.tab-help.scss
  stylesheets/_component.toggle-switch.scss
  stylesheets/_component.toolbar.scss
  stylesheets/_structure.scaffolding.scss
Labels: CMS, CXM, enhancement

#893 Remove Wraith tests due to lack of use
  Gruntfile.js
  docs/tagging.md
  makefile
  tests/css/DiffTest.php
  tests/css/updateWraith.php
  wraith.yml
Labels: tests

#925 Allow settings UI with large tab__content to appropriately allow scrolling
  stylesheets/_layout.settings.scss
Labels: bug
