Repository jadu/pulsar, pull requests merged in 2019-03, with the labels that each got.

#946 Jumping to a #fragment should no longer cause the search bar to be obscured
  stylesheets/_structure.scaffolding.scss
Labels: bug, patch

#943 Fix inputs not meeting WCAG 2.1 colour contrast
  stylesheets/_component.forms.scss
  stylesheets/_component.range-slider.scss
  stylesheets/_component.search.scss
  stylesheets/_component.select2.scss
  stylesheets/_component.toggle-switch.scss
  stylesheets/_palette.base.scss
Labels: a11y, bug, minor

#947 Fix text colour for legend based form labels
  stylesheets/_component.forms.scss
  stylesheets/_palette.base.scss
Labels: bug, patch

#952 Fix mobile swipe issue
  stylesheets/_component.tab-help.scss
  stylesheets/_structure.scaffolding.scss
Labels: bug

#953 Reverting earlier pagination changes
  stylesheets/_component.datatables.scss
  stylesheets/_component.pagination.scss
Labels: bug
