Repository jadu/pulsar, pull requests merged in 2019-11, with the labels that each got.

#1014 Switch off autocomplete on pikaday date pickers
  js/PulsarFormComponent.js
Labels: bug

#1027 Turn off vertical shift when remove buttons are hovered
  stylesheets/_component.remove-button.scss
Labels: bug

#1031 Fix issue causing modules with no pages to be incorrectly unselected
  js/ModulePermissionsComponent.js
  stylesheets/_component.forms.scss
Labels: bug, patch

#1015 Stop settings sidebar from having a large margin in XFP when sticky sidebar switches off
  stylesheets/_layout.settings.scss
Labels: XFP, bug

#1025 Fix issue preventing DataTables from adopting horizontal scroll behaviour
  js/PulsarUIComponent.js
  stylesheets/_component.datatables.scss
  views/pulsar/v2/helpers/html.html.twig
Labels: bug

#1002 Increase contrast of light text palette colour to meet AA
  stylesheets/_palette.base.scss
Labels: a11y

#1003 Increase contrast of continuum brandmark used in footer
  images/branding/jadu-continuum-brandmark.png
  images/branding/jadu-continuum-brandmark.svg
  views/pulsar/layouts/base.html.twig
Labels: a11y

#1033 Updated focus styles
  images/branding/logo-cms-black.svg
  images/branding/logo-cp-black.svg
  images/branding/logo-cxm-black.svg
  images/branding/logo-xfp-black.svg
  stylesheets/_component.breadcrumb.scss
  stylesheets/_component.button-groups.scss
  stylesheets/_component.buttons.scss
  stylesheets/_component.close.scss
  stylesheets/_component.colorpicker.scss
  stylesheets/_component.datatables.scss
  stylesheets/_component.dropdowns.scss
  stylesheets/_component.filterbar.scss
  stylesheets/_component.flash.scss
  stylesheets/_component.forms.scss
  stylesheets/_component.modals.scss
  stylesheets/_component.navigation.scss
  stylesheets/_component.pagination.scss
  stylesheets/_component.progress-lists.scss
  stylesheets/_component.range-slider.scss
  stylesheets/_component.rules.scss
  stylesheets/_component.search.scss
  stylesheets/_component.select2.scss
  stylesheets/_component.tab-help.scss
  stylesheets/_component.table-detail.scss
  stylesheets/_component.tables.scss
  stylesheets/_component.toggle-switch.scss
  stylesheets/_component.toolbar.scss
  stylesheets/_config.branding.scss
  stylesheets/_config.theme.scss
  stylesheets/_mixin.focus.scss
  stylesheets/_mixin.mixins-to-organise.scss
  stylesheets/_palette.base.scss
  stylesheets/_structure.scaffolding.scss
  stylesheets/_utility.utilities.scss
  stylesheets/pulsar.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-default.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-info.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-success.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-warning.html
  views/lexicon/forms/text.html.twig
  views/lexicon/includes/button-grid_links.html.twig
  views/lexicon/tables/datatable.html.twig
  views/lexicon/tabs/buttons_labels.html.twig
  views/lexicon/tabs/cards.html.twig
  views/pulsar/v2/helpers/flash.html.twig
Labels: a11y, major, section 508, 🔥 breaking change

#1005 Base layout changes to provide new landmarks
  js/HelpTextComponent.js
  stylesheets/_component.flash.scss
  stylesheets/_component.navigation.scss
  stylesheets/_component.search.scss
  stylesheets/_component.toolbar.scss
  stylesheets/_config.variables.scss
  stylesheets/_layout.tabs.scss
  tests/js/web/FlashMessageComponentTest.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-default.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-info.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-non-dismissable.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-success.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/flash/flash-warning.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href-with-src-active.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-url-href-with-src.html
  views/playground/xfp-received/index.html.twig
  views/pulsar/components/tab.html.twig
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/flash.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: a11y, enhancement, 🔥 breaking change

#1039 Update jsTree to address potential vulnerability
  package-lock.json
  package.json
Labels: CMS, chore

#1043 Tidy up and reorganisation of utilities stylesheet
  stylesheets/_utility.utilities.scss
Labels: chore, documentation

#1049 Fix issue preventing IE11 from removing repeater placeholders
  js/Repeater/RepeaterComponent.js
  js/Repeater/RepeaterPlaceholderService.js
Labels: bug

#1037 Improve disabled links javascript
  js/PulsarUIComponent.js
  stylesheets/_component.buttons.scss
  stylesheets/_structure.scaffolding.scss
  stylesheets/_structure.type.scss
  tests/js/web/PulsarUIComponentTest.js
  views/lexicon/tabs/buttons_labels.html.twig
Labels: bug

#1076 Fix the twig deprecation issue while CMS upgrades to Symfony 3.4
  views/pulsar/components/tab.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: bug

#1088 Bump jadu/selectWoo to 1.1.1
  package-lock.json
  package.json
Labels: accessibility, chore

#1087 Lexicon fixes
  stylesheets/_component.breadcrumb.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html
  views/lexicon/base.html.twig
  views/lexicon/forms/all.html.twig
  views/lexicon/forms/button-group.html.twig
  views/lexicon/forms/checkbox.html.twig
  views/lexicon/forms/choice.html.twig
  views/lexicon/forms/colour.html.twig
  views/lexicon/forms/compound.html.twig
  views/lexicon/forms/content.html.twig
  views/lexicon/forms/date.html.twig
  views/lexicon/forms/file.html.twig
  views/lexicon/forms/password.html.twig
  views/lexicon/forms/radio.html.twig
  views/lexicon/forms/range.html.twig
  views/lexicon/forms/repeater.html.twig
  views/lexicon/forms/select.html.twig
  views/lexicon/forms/select2.html.twig
  views/lexicon/forms/text.html.twig
  views/lexicon/forms/textarea.html.twig
  views/lexicon/forms/time.html.twig
  views/lexicon/forms/toggle-switch.html.twig
  views/lexicon/includes/notifications.html.twig
  views/lexicon/patterns/disabled-ui/disabled-ui.html.twig
  views/lexicon/patterns/error-summary/error-summary.html.twig
  views/lexicon/patterns/filters/create-filter.html.twig
  views/lexicon/patterns/filters/load-filter.html.twig
  views/lexicon/patterns/masterswitch/masterswitch-disabled-form-wrapper.html.twig
  views/lexicon/patterns/masterswitch/masterswitch-enabled-form-wrapper.html.twig
  views/lexicon/patterns/masterswitch/masterswitch-enabled.html.twig
  views/lexicon/patterns/masterswitch/masterswitch.html.twig
  views/lexicon/patterns/no-results/table.html.twig
  views/lexicon/patterns/reporting/report.html.twig
  views/lexicon/patterns/rules/one.html.twig
  views/lexicon/patterns/settings/index.html.twig
  views/lexicon/patterns/settings/tab.html.twig
  views/lexicon/patterns/table-detail/table-detail.html.twig
  views/lexicon/tables.html.twig
  views/lexicon/tables/basic-scrolling.html.twig
  views/lexicon/tables/basic.html.twig
  views/lexicon/tables/sortable.html.twig
  views/lexicon/tabs/analytics.html.twig
  views/lexicon/tabs/buttons_labels.html.twig
  views/lexicon/tabs/filters.html.twig
  views/lexicon/tabs/flash.html.twig
  views/lexicon/tabs/loading.html.twig
  views/lexicon/tabs/message.html.twig
  views/lexicon/tabs/pagination.html.twig
  views/lexicon/tabs/panels.html.twig
  views/lexicon/tabs/progress_bars.html.twig
  views/pulsar/components/nav_help.html.twig
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/html.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: accessibility, bug

#1089 Form helper option/attribute fixes
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/compound-mixed.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/content-disabled.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/content-disabled.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-placeholder.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-placeholder.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/range-placeholder.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/range-placeholder.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/range-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/range-required.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append-button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append-button.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-prepend-button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-prepend-button.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1091 Make select2 multiples the same initial height as singles
  stylesheets/_component.select2.scss
Labels: bug
