Repository jadu/pulsar, pull requests merged in 2019-02, with the labels that each got.

#937 Fixed h scrolling table actions menu link issue
  stylesheets/_component.tables.scss
Labels: bug, patch

#941 Close quaternary menu when more icon is clicked a second time
  js/NavMainComponent.js
  tests/js/web/NavMainComponentTest.js
Labels: bug

#892 New sandboxed styles for XFP conditional logic rules
  stylesheets/_component.rules.scss
  stylesheets/_config.variables.scss
  views/playground/xfp-rules/rules.html.twig
Labels: feature
