Repository jadu/pulsar, pull requests merged in 2020-08, with the labels that each got.

#1286 Fix modal focus issues
  js/Modals/ModalFocusService.js
  tests/js/web/Modals/ModalFocusServiceTest.js
  views/lexicon/tabs/modals.html.twig
Labels: accessibility

#1287 Remove hardcoded actions menu ID causing dup ID validation failures in JS tabs
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu-dividers.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu-items.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu.html
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, bug

#1285 Select woo jadu 1.1.3
  package-lock.json
  package.json
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-multiple.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-multiple.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-single.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-single.html.twig
  views/lexicon/forms/select2.html.twig
  views/pulsar/v2/helpers/elem.html.twig
Labels: accessibility, bug

#1284 Filterbar select2 placeholder and tab.js fixes
  js/FilterBarComponent.js
  js/HelpTextComponent.js
  js/PulsarFormComponent.js
  js/TabEnhancements/TabEnhancements.js
  js/index.js
  js/libs/tab.js
  js/main.js
  tests/js/web/FilterBarComponentTest.js
  tests/js/web/PulsarFormComponentTest.js
  tests/js/web/TabEnhancements/TabEnhancementsTest.js
  views/lexicon/patterns/filters/create-filter.html.twig
  views/lexicon/patterns/filters/load-filter.html.twig
Labels: CMS, bug

#1277 Rules UI a11y updates
  js/PulsarUIComponent.js
  stylesheets/_component.rules.scss
  views/lexicon/patterns/rules/event-based.html.twig
  views/lexicon/patterns/rules/index.html.twig
  views/lexicon/patterns/rules/logic-based.html.twig
  views/lexicon/tables/datatable-collapse.html.twig
  views/lexicon/tables/datatable.html.twig
  views/playground/xfp-rules/index.html.twig
  views/playground/xfp-rules/rules.html.twig
  views/playground/xfp-rules/templates.html.twig
  views/pulsar/v2/helpers/rules.html.twig
Labels: accessibility, documentation, 🔥 breaking change

#1281 Add some missing tests for required attribute
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-required.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-required.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-required.html.twig
Labels: tests

#1272 Space form actions with margin rather than whitespace
  stylesheets/_component.forms.scss
  views/pulsar/v2/helpers/form.html.twig
Labels: enhancement
