Repository jadu/pulsar, pull requests merged in 2020-03, with the labels that each got.

#1145 Added role=“search” to main search form
  views/pulsar/layouts/base.html.twig
  views/pulsar/layouts/pulsar.html.twig
Labels: accessibility

#1151 Update lexicon tooltip examples with new tooltips
  views/lexicon/includes/notifications.html.twig
  views/lexicon/patterns/reporting/building.html.twig
  views/lexicon/patterns/reporting/report.html.twig
  views/lexicon/tabs/buttons_labels.html.twig
  views/lexicon/tabs/modals.html.twig
Labels: chore

#1126 Hide add-filter button when all filters in a loaded filter have been used
  js/FilterBarComponent.js
  tests/js/web/FilterBarComponentTest.js
Labels: bug

#1152 Update helper tooltips
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-input.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-link.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-placements.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-submit.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-target.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-actions.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-link.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-placements.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-submit.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-target.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button.html
  views/pulsar/v2/helpers/html.html.twig
  views/pulsar/v2/helpers/pulsar.html.twig
  views/pulsar/v2/helpers/rules.html.twig
  views/pulsar/v2/helpers/util.html.twig
Labels: accessibility

#1154 Fix SR issues with required indicator and status helper
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
  views/pulsar/v2/helpers/html.html.twig
  views/pulsar/v2/helpers/util.html.twig
Labels: accessibility

#1156 Datatables column toggle improvements
  js/PulsarUIComponent.js
  stylesheets/_component.datatables.scss
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility

#1160 Fix flash message positioning and spacing improvements
  stylesheets/_component.flash.scss
  stylesheets/_component.ribbon.scss
  stylesheets/_component.toolbar.scss
  stylesheets/_layout.tabs.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
  views/pulsar/components/flash.html.twig
  views/pulsar/layouts/base.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, bug

#1157 Prevent modals closing on body click
  js/libs/modal.js
Labels: accessibility

#1159 Modal focus a11y improvements
  js/Modals/ModalFocusService.js
  js/Modals/ModalListener.js
  js/index.js
  js/libs/modal.js
  js/main.js
  tests/js/web/ModalTest.js
  tests/js/web/Modals/ModalFocusServiceTest.js
  tests/js/web/Modals/ModalListenerTest.js
  views/lexicon/tabs/modals.html.twig
Labels: accessibility, major, 🔥 breaking change

#1186 Improve link hover style
  stylesheets/_component.breadcrumb.scss
  stylesheets/_palette.base.scss
Labels: accessibility, patch

#1187 html.label improvements
  stylesheets/_component.labels.scss
  stylesheets/_mixin.focus.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable-states.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, bug

#1190 Fix range focus site improve error
  stylesheets/_mixin.focus.scss
Labels: accessibility, bug

#1191 Remove aria-required from form elements with the required attribute
  src/Jadu/Pulsar/Twig/Extension/AttributeParserExtension.php
  tests/unit/Jadu/Pulsar/Twig/Extension/AttributeParserExtensionTest.php
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1189 Fix landmark and SR issues with mobile help side bar
  js/HelpTextComponent.js
  tests/js/web/HelpTextComponentTest.js
  views/pulsar/layouts/base.html.twig
Labels: accessibility, bug

#1192 Add aria-disabled attribute to disabled UI wrapper and change text color for disabled links
  js/DisableUiComponent.js
  js/PulsarUIComponent.js
  stylesheets/_component.forms.scss
  stylesheets/_utility.utilities.scss
  tests/js/web/DisableUiComponentTest.js
  tests/js/web/PulsarUIComponentTest.js
  views/lexicon/patterns/disabled-ui/disabled-ui.html.twig
Labels: accessibility

#1194 Fix SI error by properly hiding hidden fields
  js/Repeater/RepeaterDataService.js
  tests/js/web/Repeater/RepeaterDataServiceTest.js
Labels: accessibility, bug

#1193 Fixed panel cta contrast issue and related lexicon a11y tool errors
  stylesheets/_component.panels.scss
  stylesheets/_component.timeline.scss
  views/lexicon/tabs/panels.html.twig
Labels: accessibility, bug

#1196 Dropzone a11y improvements
  js/DropZone/DropZoneComponent.js
  js/DropZone/DropZoneComponentUtils.js
  stylesheets/_component.dropzone.scss
  tests/js/web/DropZone/DropZoneComponentUtilsTest.js
  views/lexicon/forms/dropzone.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, enhancement

#1198 form.button_group a11y fixes
  stylesheets/_component.choice.scss
  stylesheets/_component.forms.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance-container.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-help.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-label-hide.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-label.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_checkbox.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_radio.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group.html
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1195 Add accessible label for user guides toolbar button
  docker-compose.yml
  views/pulsar/components/nav_help.html.twig
  views/pulsar/v2/helpers/nav.html.twig
Labels: accessibility

#1199 Stop form helpers adding aria-invalid to generated markup
  codecov.yml
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/password-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-error.html
  views/pulsar/v2/helpers/elem.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility

#1142 Restore ability to switch off datatable row selection with a data attribute
  js/PulsarUIComponent.js
  stylesheets/_component.datatables.scss
  tests/js/web/PulsarUIComponentTest.js
  views/lexicon/tables/datatable.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: bug
