Repository jadu/pulsar, pull requests merged in 2020-05, with the labels that each got.

#1224 Date picker improvements
  js/area/signin/signin.js
  js/index.js
  js/main.js
  package-lock.json
  package.json
  stylesheets/pulsar.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker-format.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker-format.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker-label.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker-label.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-pulsar-date-picker.html.twig
  views/lexicon/forms/date.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility

#1238 Repeater focus management
  js/FocusManagementService.js
  js/Repeater/InputCloneService.js
  js/Repeater/InputReplacementService.js
  js/Repeater/RepeaterComponent.js
  js/Repeater/RepeaterDataService.js
  js/Repeater/RepeaterPlaceholderService.js
  js/Repeater/RepeaterPreviewService.js
  js/Repeater/repeaterComponentFactory.js
  js/Repeater/repeaterConfig.js
  js/utilities/QueryService.js
  js/utilities/UniqueIdService.js
  tests/js/web/FocusManagementServiceTest.js
  tests/js/web/Repeater/InputCloneServiceTest.js
  tests/js/web/Repeater/InputReplacementServiceTest.js
  tests/js/web/Repeater/RepeaterComponentTest.js
  tests/js/web/Repeater/RepeaterDataServiceTest.js
  tests/js/web/Repeater/RepeaterPlaceholderServiceTest.js
  tests/js/web/Repeater/RepeaterPreviewServiceTest.js
  tests/js/web/utilities/QueryServiceTest.js
  views/lexicon/forms/repeater.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, bug

#1235 Removable label enhancements
  js/FilterBarComponent.js
  stylesheets/_component.labels.scss
  stylesheets/_mixin.focus.scss
  stylesheets/_mixin.label-variant.scss
  tests/js/web/FilterBarComponentTest.js
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable-states.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, bug

#1218 Stop selects needing two clicks to open in Firefox
  stylesheets/_component.forms.scss
Labels: bug

#1212 Make sure pagination sits directly under datatable
  stylesheets/_component.datatables.scss
Labels: bug
