Repository jadu/pulsar, pull requests merged in 2020-06, with the labels that each got.

#1245 Datatables accessibility improvements
  js/DataTables/dataTablesDrawCallback.js
  js/DataTables/dataTablesInitComplete.js
  js/PulsarUIComponent.js
  tests/js/web/DataTables/dataTablesDrawCallbackTest.js
  tests/js/web/DataTables/dataTablesInitCompleteTest.js
  views/lexicon/tables/basic-scrolling.html.twig
  views/lexicon/tables/basic.html.twig
  views/lexicon/tables/datatable-collapse.html.twig
  views/lexicon/tables/datatable-empty.html.twig
  views/lexicon/tables/datatable.html.twig
  views/lexicon/tables/sortable.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility

#1249 Ensure interactive elements in closed mobile sidebar cannot be focussed or seen by SRs
  js/HelpTextComponent.js
  tests/js/web/HelpTextComponentTest.js
Labels: accessibility

#1244 Make indented fields adjust their total width by subtracting the label width
  stylesheets/_component.forms.scss
  stylesheets/_structure.grid.scss
Labels: bug

#1248 Improve alignment of page selections with settings UI
  stylesheets/_layout.settings.scss
  views/playground/branding/branding.html.twig
  views/playground/branding/index.html.twig
Labels: bug

#1241 Stop focused nav items being obscured by hovered items
  stylesheets/_component.navigation.scss
Labels: bug

#1240 Remove 99% width constraint from textareas
  stylesheets/_structure.forms.scss
Labels: enhancement

#1253 Improve contrast of notifications dismiss button
  stylesheets/_component.notifications.scss
  stylesheets/_component.remove-button.scss
Labels: accessibility

#1260 Notifications fixes
  stylesheets/_component.notifications.scss
  stylesheets/_palette.base.scss
  views/lexicon/includes/notifications.html.twig
  views/pulsar/v2/helpers/pulsar.html.twig
Labels: accessibility, bug

#1261 Remove/Edit icon button focus styles
  stylesheets/_component.edit-button.scss
  stylesheets/_component.remove-button.scss
  stylesheets/_component.tables.scss
  stylesheets/_mixin.focus.scss
  stylesheets/_utility.utilities.scss
  stylesheets/pulsar.scss
  views/lexicon/tables/form-tables.html.twig
  views/lexicon/tables/sortable.html.twig
  views/lexicon/tabs/datagrid.html.twig
Labels: accessibility

#1262 Lexicon SI fixes
  views/lexicon/forms/all.html.twig
  views/lexicon/forms/checkbox.html.twig
  views/lexicon/forms/radio.html.twig
  views/lexicon/forms/toggle-switch.html.twig
Labels: accessibility

#1263 JStree a11y review fixes
  stylesheets/_component.jstree.scss
Labels: accessibility

#1256 Fix modal examples in Lexicon
  views/lexicon/tabs/modals.html.twig
Labels: documentation

#1264 Common list pattern a11y audit fixes
  js/PulsarUIComponent.js
  views/lexicon/patterns/common-list/table.html.twig
Labels: accessibility

#1265 A11y disabledui/masterswitch audit fixes
  js/DisableUiComponent.js
  tests/js/web/DisableUiComponentTest.js
  views/lexicon/patterns/masterswitch/masterswitch-disabled-form-wrapper.html.twig
  views/lexicon/patterns/masterswitch/masterswitch-enabled-form-wrapper.html.twig
  views/lexicon/patterns/masterswitch/masterswitch-enabled.html.twig
  views/lexicon/patterns/masterswitch/masterswitch.html.twig
Labels: accessibility

#1257 a11y improvements to main nav
  js/FocusManagementService.js
  js/NavMainComponent.js
  js/index.js
  js/main.js
  stylesheets/_component.navigation.scss
  stylesheets/_layout.tabs.scss
  tests/js/web/FocusManagementServiceTest.js
  tests/js/web/NavMainComponentTest.js
  views/pulsar/v2/helpers/nav.html.twig
Labels: accessibility

#1269 Piano a11y updates
  images/services/address_finder.png
  images/services/aws_lex.png
  images/services/cxm.png
  images/services/mailgun.png
  images/services/smtp_server.png
  stylesheets/_component.piano.scss
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-actions.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon-color.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-no-alt.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-type.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media.html
  views/lexicon/base.html.twig
  views/lexicon/patterns/piano/aws.html.twig
  views/lexicon/patterns/piano/deployer.html.twig
  views/lexicon/patterns/piano/index.html.twig
  views/lexicon/patterns/piano/mailgun.html.twig
  views/lexicon/patterns/piano/singlepoint.html.twig
  views/lexicon/patterns/piano/tab_address_finder.html.twig
  views/lexicon/patterns/piano/tab_aws.html.twig
  views/lexicon/patterns/piano/tab_deployer.html.twig
  views/lexicon/patterns/piano/tab_mailgun.html.twig
  views/lexicon/patterns/piano/tab_messages.html.twig
  views/lexicon/patterns/piano/tab_singlepoint.html.twig
  views/playground/integrations/singlepoint_five.html.twig
  views/playground/integrations/singlepoint_four.html.twig
  views/playground/integrations/singlepoint_one.html.twig
  views/playground/integrations/singlepoint_six.html.twig
  views/playground/integrations/singlepoint_three.html.twig
  views/playground/integrations/singlepoint_two.html.twig
  views/playground/integrations/six.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, enhancement
