Repository jadu/pulsar, pull requests merged in 2020-09, with the labels that each got.

#1299 Make updates
  makefile
Labels: tooling

#1301 Various lexicon a11y fixes
  stylesheets/_utility.sortable.scss
  stylesheets/_utility.swatches.scss
  views/lexicon/patterns/no-results/table.html.twig
  views/lexicon/patterns/table-detail/table-detail-collapsing.html.twig
  views/lexicon/tables.html.twig
  views/lexicon/tables/form-tables.html.twig
  views/lexicon/tables/sortable.html.twig
  views/lexicon/tabs/loading.html.twig
  views/lexicon/tabs/message.html.twig
  views/lexicon/tabs/tooltips.html.twig
  views/lexicon/tabs/tooltips_v2.html.twig
  views/lexicon/utilities/responsive.html.twig
Labels: accessibility

#1211 Restrict toggle activation to the control label and the toggle control only
  js/PulsarFormComponent.js
  tests/js/web/PulsarFormComponentTest.js
Labels: enhancement

#1312 Ensure AA contrast of links within state containers
  stylesheets/_utility.states.scss
Labels: accessibility

#1310 Darken help text to fix contrast warning in IBM a11y tool
  stylesheets/_palette.base.scss
Labels: accessibility

#1313 Ensure AA contrast for help/warning states within table forms
  stylesheets/_component.forms.scss
Labels: accessibility

#1297 Add tab header to sit above tab settings and tab content
  stylesheets/_layout.settings.scss
  views/lexicon/patterns/settings-panel/tab.html.twig
  views/lexicon/patterns/tab-header/index.html.twig
  views/lexicon/patterns/tab-header/table.html.twig
  views/pulsar/components/tab.html.twig
Labels: feature

#1320 Make sure horizontal scrollbar is visible for tabbed navigation inside piano content
  stylesheets/_component.piano.scss
Labels: bug

#1322 Set a consistent font size for card titles so that any heading tag can be used
  stylesheets/_component.cards.scss
Labels: enhancement

#1323 Stop flush inputs inheriting nowrap from horizontal table cells
  stylesheets/_component.tables.scss
Labels: bug

#1319 Lighten table form backgrounds to fix error contrast
  stylesheets/_component.forms.scss
  stylesheets/_component.tables.scss
Labels: accessibility

#1325 Make sure help blocks wrap properly when in a table—horizontal form
  stylesheets/_component.forms.scss
Labels: bug

#1324 Fix contrast issue when danger text/icon colour appears in a table row with hover effect
  stylesheets/_palette.base.scss
Labels: accessibility
