Repository jadu/pulsar, pull requests merged in 2021-01, with the labels that each got.

#1350 Fix colour contrast issue of warning progress bar with value
  stylesheets/_component.progress-bars.scss
  views/lexicon/tabs/progress_bars.html.twig
Labels: accessibility, bug, patch

#1354 Update browser-sync and favicon npm packages
  package-lock.json
  package.json
Labels: dependencies

#1332 Fix vertical alignment of choice block labels
  CHANGELOG.md
  stylesheets/_component.choice.scss
  stylesheets/_component.forms.scss
Labels: bug

#1331 Stop extracting text from a DOM node and interpreting as HTML
  CHANGELOG.md
  js/DropZone/DropZoneValidationUtils.js
  js/FilterBarComponent.js
  js/PulsarSortableComponent.js
  js/libs/modal.js
  js/libs/tab.js
  js/libs/tooltip.js
Labels: chore

#1330 Make sure span labels display as expected with form__group—top
  CHANGELOG.md
  stylesheets/_structure.forms.scss
Labels: bug

#1314 Add ability for textareas to use appended/prepended options
  CHANGELOG.md
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-append-button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-append-button.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-append.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-append.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-prepend-button.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-prepend-button.html.twig
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-prepend.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-prepend.html.twig
  views/lexicon/forms/textarea.html.twig
  views/pulsar/v2/helpers/form.html.twig
Labels: feature

#1360 Add tight spacing option for form groups
  CHANGELOG.md
  stylesheets/_structure.forms.scss
Labels: feature, scratch rule in use

#1361 Table caption styling
  CHANGELOG.md
  stylesheets/_component.tables.scss
  views/lexicon/tables/basic.html.twig
Labels: accessibility, patch

#1364 Prepend form error text with visually hidden “Error:”
  CHANGELOG.md
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/content-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/error-multiple.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/error-single.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/password-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-error.html
  tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-error.html
  views/pulsar/v2/helpers/form.html.twig
Labels: accessibility, enhancement, minor

#1370 Added CK editor focus styles
  stylesheets/_component.forms.scss
Labels: enhancement, patch, scratch rule in use

#1358 Update axios package to address security vulnerability
  package-lock.json
  package.json
Labels: dependencies

#1351 Switch grunt sass to use dart-sass
  Gruntfile.js
  package-lock.json
  package.json
  stylesheets/_component.badges.scss
  stylesheets/_component.button-groups.scss
  stylesheets/_component.buttons.scss
  stylesheets/_component.cards.scss
  stylesheets/_component.dropzone.scss
  stylesheets/_component.flash.scss
  stylesheets/_component.icons.scss
  stylesheets/_component.input-groups.scss
  stylesheets/_component.labels.scss
  stylesheets/_component.panels.scss
  stylesheets/_component.tables.scss
  stylesheets/_palette.base.scss
  stylesheets/_utility.states.scss
  stylesheets/_utility.swatches.scss
Labels: tooling

#1362 Update homebrew installation script in makefile
  CHANGELOG.md
  makefile
Labels: bug, tooling

#1363 Added scope=“col” to repeater and datatable th’s
  CHANGELOG.md
  views/pulsar/v2/helpers/form.html.twig
  views/pulsar/v2/helpers/html.html.twig
Labels: accessibility, enhancement, patch
